apiVersion: v1
kind: Service
metadata:
  name: blockassembly-service

  labels:
    app: blockassembly
  annotations:
    prometheus.io/port: "9091"
    prometheus.io/scrape: "true"
spec:
  clusterIP: None
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
  selector:
    app: blockassembly
  ports:
    - name: tcp
      port: 8085
      targetPort: 8085
      protocol: TCP
    - name: frpc
      port: 8285
      targetPort: 8285
      protocol: TCP
    - name: profiler
      port: 9091
      targetPort: 9091
      protocol: TCP
    - name: debugger
      port: 4040
      targetPort: 4040
      protocol: TCP
