apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
<<<<<<< Updated upstream:deploy/k8s/base/allinone-miner/service-account.yaml
    eks.amazonaws.com/role-arn: arn:aws:iam::434394763103:role/eks-s3-role-pusher
  name: sa-a
=======
    eks.amazonaws.com/role-arn: arn:aws:iam::434394763103:role/eks-s3-role-pusher #region
  name: sa-t
>>>>>>> Stashed changes:deploy/k8s/base/service-account.yaml
