#apiVersion: v1
#kind: Service
#metadata:
#  name: txmetastore-service
#
#  labels:
#    app: txmetastore
#  annotations:
#    prometheus.io/port: "9091"
#    prometheus.io/scrape: "true"
#spec:
#  clusterIP: None
#  ipFamilyPolicy: SingleStack
#  ipFamilies:
#  - IPv4
#  selector:
#    app: txmetastore
#  ports:
#    - name: profiler
#      port: 9091
#      targetPort: 9091
#      protocol: TCP
#    - name: delve
#      port: 4040
#      targetPort: 4040
#      protocol: TCP
