#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: utxostore
#
#  labels:
#    app: utxostore
#    project: service
#spec:
#  replicas: 0
#  selector:
#    matchLabels:
#      app: utxostore
#  template:
#    metadata:
#      labels:
#        app: utxostore
#    spec:
#      serviceAccountName: miner-service-account
#      affinity:
#        podAntiAffinity:
#          preferredDuringSchedulingIgnoredDuringExecution:
#            - weight: 100
#              podAffinityTerm:
#                labelSelector:
#                  matchLabels:
#                    app: utxostore
#                topologyKey: "kubernetes.io/hostname"
#      tolerations:
#        - key: type
#          value: massive
#          operator: Equal
#          effect: NoSchedule
#      containers:
#        - name: utxostore
#          image: 434394763103.dkr.ecr.eu-north-1.amazonaws.com/ubsv:latest-arm64
#          args: [ "-utxostore=1" ]
#          # command: "You can override the entrypoint with a command."
#          #          command: ["./dlv", "--listen=:4040", "--continue", "--accept-multiclient", "--headless=true", "--api-version=2", "exec", "./ubsv.run", "--"]
#          #          command: [ "./ubsv.run" ]
#          envFrom:
#            - configMapRef:
#                name: utxo-config-m1 # todo fix to dynmaically get numebr of miner
#          env:
#            - name: SERVICE_NAME
#              value: utxostore-service
#          ports:
#            - containerPort: 4040
#              protocol: TCP
#            - containerPort: 8082
#              protocol: TCP
#            - containerPort: 9091
#              protocol: TCP
#          resources:
#            requests:
#              memory: 32Gi
#              cpu: "100"
#            limits:
#              memory: 32Gi
#              cpu: "100"
#          readinessProbe:
#            httpGet:
#              path: /health
#              port: 9091
#            initialDelaySeconds: 1
#            periodSeconds: 10
#            failureThreshold: 5
#            timeoutSeconds: 3
#          livenessProbe:
#            httpGet:
#              path: /health
#              port: 9091
#            initialDelaySeconds: 1
#            periodSeconds: 10
#            failureThreshold: 5
#            timeoutSeconds: 3
