#apiVersion: v1
#kind: ConfigMap
#metadata:
#  name: utxo-config
#data:
#  SETTINGS_CONTEXT:  "scaling.m1.memory"
#  JAEGER_AGENT_HOST: jaeger-cluster-agent.jaeger.svc.cluster.local
#  JAEGER_AGENT_PORT: "6831"
