apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: tcp-8091-asset-miner
  labels:
    service: miner
  annotations:
    kubernetes.io/ingress.class: "traefik-allinone"
spec:
  entryPoints:
    - ast-grpc
  routes:
  - match: HostSNI(`*`)
    services:
    - name: miner
      port: 8091
  