apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: tcp-80-http-asset-miner
  labels:
    service: miner
spec:
  entryPoints:
    - miner
  routes:
  - match: Host(`miner.allinone.ubsv.dev`)
    kind: Rule
    services:
    - name: miner
      port: 8090
