apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: tcp-443-https-blob-miner
  labels:
    service: miner
spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`miner.allinone.ubsv.dev`)
    services:
    - name: miner
      port: 8090
      terminationDelay: 400
  tls:
    passthrough: true
