apiVersion: apps/v1
kind: Deployment
metadata:
  name: miner
  namespace: miner
  labels:
    service: miner
    project: miner
spec:
  replicas: 1
  selector:
    matchLabels:
      service: miner
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        service: miner
    spec:
      serviceAccountName: miner-sa
      # affinity to attempt as much as possible not to schedule same instance types on the same k8s host/node
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    service: miner
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: miner
          image: REPO:IMAGE:TAG
          #          command: [ "./dlv", "--listen=:4040", "--continue", "--accept-multiclient", "--headless=true", "--api-version=2", "exec", "./ubsv.run", "--" ]
          args: [ ]
          envFrom:
            - configMapRef:
                name: config-miner
          env: 
            - name: "blockchain_store"
              value: "postgres://postgres:postgres@localhost:5432/blockchain"
            - name: "coinbase_store"
              value: "postgres://postgres:postgres@localhost:5432/coinbase"
            - name: "txmeta_store"
              value: "postgres://postgres:postgres@localhost:5432/txmeta"
            - name: "utxostore"
              value: "postgres://postgres:postgres@localhost:5432/utxostore"
          ports:
            - containerPort: 4040
              protocol: TCP
            - containerPort: 8084
              protocol: TCP
            - containerPort: 8087
              protocol: TCP
            - containerPort: 8093
              protocol: TCP
            - containerPort: 8090
              protocol: TCP
            - containerPort: 8091
              protocol: TCP
            - containerPort: 8097
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
            - containerPort: 9905
              protocol: TCP
            - containerPort: 9906
              protocol: TCP
            - containerPort: 8384
              protocol: UDP
          resources:
            requests:
              memory: 15Gi
              cpu: "8"
            limits:
              memory: 15Gi
              cpu: "8"
          volumeMounts:
            - mountPath: /data/subtreestore-ttl/
              name: subtree-store-ttl
          readinessProbe:
            # run grpcurl command
            exec:
              command:
                - /bin/sh
                - -c
                # this hacky but siggi and joe agreed to do it that way because all in one configuration is just for testing
                - grpcurl -insecure localhost:8093 coinbase_api.CoinbaseAPI.Health && grpcurl -insecure localhost:8084 propagation_api.PropagationAPI.Health && grpcurl -insecure localhost:8081 validator_api.ValidatorAPI.Health && grpcurl -insecure localhost:8087 blockchain_api.BlockchainAPI.Health && grpcurl -insecure localhost:8091 asset_api.AssetAPI.Health && grpcurl -insecure localhost:8085 blockassembly_api.BlockAssemblyAPI.Health && grpcurl -insecure localhost:8088 blockvalidation_api.BlockValidationAPI.Health
            initialDelaySeconds: 1
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
          livenessProbe:
            # run grpcurl command
            exec:
              command:
                - /bin/sh
                - -c
                # this hacky but siggi and joe agreed to do it that way because all in one configuration is just for testing
                - grpcurl -insecure localhost:8093 coinbase_api.CoinbaseAPI.Health && grpcurl -insecure localhost:8084 propagation_api.PropagationAPI.Health && grpcurl -insecure localhost:8081 validator_api.ValidatorAPI.Health && grpcurl -insecure localhost:8087 blockchain_api.BlockchainAPI.Health && grpcurl -insecure localhost:8091 asset_api.AssetAPI.Health && grpcurl -insecure localhost:8085 blockassembly_api.BlockAssemblyAPI.Health && grpcurl -insecure localhost:8088 blockvalidation_api.BlockValidationAPI.Health
            initialDelaySeconds: 1
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
        - name: postgres-sidecar
          image: postgres:latest
          env:
          - name: POSTGRES_PASSWORD
            value: postgres
          volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
          - name: init-script
            mountPath: /docker-entrypoint-initdb.d
            # SubPath ensures only your script is mounted, not the entire ConfigMap directory
            subPath: create-db.sql
      volumes:
      - name: subtree-store-ttl
        ephemeral:
          volumeClaimTemplate:
            metadata:
              labels:
                type: subtreestore-ttl
            spec:
              accessModes: [ "ReadWriteOnce" ]
              storageClassName: "io2-xfs-low-iops"
              resources:
                requests:
                  storage: 1000Gi
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: init-script
        configMap:
          name: postgres-init-scripts
