apiVersion: apps/v1
kind: Deployment
metadata:
  name: miner
  namespace: miner
  labels:
    service: miner
    project: miner
spec:
  replicas: 1
  selector:
    matchLabels:
      service: miner
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        service: miner
    spec:
      serviceAccountName: miner-sa
      # affinity to attempt as much as possible not to schedule same instance types on the same k8s host/node
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    service: miner
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: miner
          image: REPO:IMAGE:TAG
          # command: [ "./dlv", "--listen=:4040", "--continue", "--accept-multiclient", "--headless=true", "--api-version=2", "exec", "./ubsv.run", "--" ]
          args: [ "-wait_for_postgres=1" ]
          envFrom:
            - configMapRef:
                name: config-miner
          env:
            - name: "postgres_check_address"
              value: "postgres-lo-1.miner-lo-1.svc.cluster.local:5432"
            - name: "blockchain_store"
              value: "postgres://postgres:postgres@postgres-lo-1.miner-lo-1.svc.cluster.local:5432/blockchain"
            - name: "coinbase_store"
              value: "postgres://postgres:postgres@postgres-lo-1.miner-lo-1.svc.cluster.local:5432/coinbase"
            - name: "txmeta_store"
              value: "postgres://postgres:postgres@postgres-lo-1.miner-lo-1.svc.cluster.local:5432/txmeta"
            - name: "utxostore"
              value: "postgres://postgres:postgres@postgres-lo-1.miner-lo-1.svc.cluster.local:5432/utxostore"

          ports:
            - containerPort: 4040
              protocol: TCP
            - containerPort: 8084
              protocol: TCP
            - containerPort: 8087
              protocol: TCP
            - containerPort: 8093
              protocol: TCP
            - containerPort: 8090
              protocol: TCP
            - containerPort: 8091
              protocol: TCP
            - containerPort: 8097
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
            - containerPort: 9905
              protocol: TCP
            - containerPort: 9906
              protocol: TCP
            - containerPort: 8384
              protocol: UDP
          resources:
            requests:
              memory: 8Gi
              cpu: "2"
            limits:
              memory: 8Gi
              cpu: "2"
          volumeMounts:
            - mountPath: /data/subtreestore-ttl/
              name: subtree-store-ttl
          readinessProbe:
            # run grpcurl command
            exec:
              command:
                - /bin/sh
                - -c
                # this hacky but siggi and joe agreed to do it that way because all in one configuration is just for testing
                - grpcurl -plaintext localhost:8093 coinbase_api.CoinbaseAPI.HealthGRPC && grpcurl -plaintext localhost:8084 propagation_api.PropagationAPI.HealthGRPC && grpcurl -plaintext localhost:8087 blockchain_api.BlockchainAPI.HealthGRPC && grpcurl -plaintext localhost:8091 asset_api.AssetAPI.HealthGRPC && grpcurl -plaintext localhost:8085 blockassembly_api.BlockAssemblyAPI.HealthGRPC && grpcurl -plaintext localhost:8088 blockvalidation_api.BlockValidationAPI.HealthGRPC
            initialDelaySeconds: 1
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
          livenessProbe:
            # run grpcurl command
            exec:
              command:
                - /bin/sh
                - -c
                # this hacky but siggi and joe agreed to do it that way because all in one configuration is just for testing
                - grpcurl -plaintext localhost:8093 coinbase_api.CoinbaseAPI.HealthGRPC && grpcurl -plaintext localhost:8084 propagation_api.PropagationAPI.HealthGRPC && grpcurl -plaintext localhost:8087 blockchain_api.BlockchainAPI.HealthGRPC && grpcurl -plaintext localhost:8091 asset_api.AssetAPI.HealthGRPC && grpcurl -plaintext localhost:8085 blockassembly_api.BlockAssemblyAPI.HealthGRPC && grpcurl -plaintext localhost:8088 blockvalidation_api.BlockValidationAPI.HealthGRPC
            initialDelaySeconds: 1
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
      volumes:
      - name: subtree-store-ttl
        persistentVolumeClaim:
          claimName: subtree-pvc
