apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: p2p-ws-ingress-9906
  labels:
    service: miner
spec:
  entryPoints:
    - p2p-ws
  routes:
    - match: HostSNI(`miner.allinone.ubsv.dev`)
      kind: Rule
      services:
        - name: miner
          port: 9906
  
