apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: p2p-ws-ingress-9906
  labels:
    service: miner
  # annotations:
  #   kubernetes.io/ingress.class: "traefik-allinone"
spec:
  entryPoints:
    - p2p-ws
  routes:
    - match: Host(`*`)
      services:
        - name: miner
          port: 9906
  