apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: p2p-ingress-tcp-9907
  labels:
    service: miner
spec:
  entryPoints:
    - p2p-grpc
  routes:
  - match: HostSNI(`miner.allinone.ubsv.dev`)
    services:
    - name: miner
      port: 9907
  tls:
    passthrough: true
