apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: p2p-ingress-9905
  labels:
    service: miner
spec:
  entryPoints:
    - p2p
  routes:
    - match: Host(`miner.allinone.ubsv.dev`)
      kind: Rule
      services:
        - name: miner
          port: 9905
