apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  create-db.sql: |
    CREATE
    DATABASE coinbase;
    CREATE
    DATABASE blockchain;
    CREATE
    DATABASE txmeta;
    CREATE
    DATABASE utxostore;