apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: miner
  labels:
    service: postgres
    project: miner
spec:
  replicas: 1
  selector:
    matchLabels:
      service: postgres
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        service: postgres
    spec:
      serviceAccountName: miner-sa
      # affinity to attempt as much as possible not to schedule same instance types on the same k8s host/node
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    service: postgres
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: postgres
          image: postgres:latest
          args: ["-c", "max_connections=1000", "-c", "listen_addresses=*"]
          env:
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: PGDATA
            value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              protocol: TCP
          resources:
            requests:
              memory: 8Gi
              cpu: "2"
            limits:
              memory: 8Gi
              cpu: "2"
          volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
          - name: init-script
            mountPath: /docker-entrypoint-initdb.d/create-db.sql
            # SubPath ensures only your script is mounted, not the entire ConfigMap directory
            subPath: create-db.sql
          # readinessProbe:
          #   # run grpcurl command
          #   exec:
          #     command:
          #       - /bin/sh
          #       - -c
          #       # this hacky but siggi and joe agreed to do it that way because all in one configuration is just for testing
          #       - grpcurl -plaintext localhost:8093 coinbase_api.CoinbaseAPI.HealthGRPC && grpcurl -plaintext localhost:8084 propagation_api.PropagationAPI.HealthGRPC && grpcurl -plaintext localhost:8087 blockchain_api.BlockchainAPI.HealthGRPC && grpcurl -plaintext localhost:8091 asset_api.AssetAPI.HealthGRPC && grpcurl -plaintext localhost:8085 blockassembly_api.BlockAssemblyAPI.HealthGRPC && grpcurl -plaintext localhost:8088 blockvalidation_api.BlockValidationAPI.HealthGRPC
          #   initialDelaySeconds: 1
          #   periodSeconds: 10
          #   failureThreshold: 5
          #   timeoutSeconds: 3
          # livenessProbe:
          #   # run grpcurl command
          #   exec:
          #     command:
          #       - /bin/sh
          #       - -c
          #       # this hacky but siggi and joe agreed to do it that way because all in one configuration is just for testing
          #       - grpcurl -plaintext localhost:8093 coinbase_api.CoinbaseAPI.HealthGRPC && grpcurl -plaintext localhost:8084 propagation_api.PropagationAPI.HealthGRPC && grpcurl -plaintext localhost:8087 blockchain_api.BlockchainAPI.HealthGRPC && grpcurl -plaintext localhost:8091 asset_api.AssetAPI.HealthGRPC && grpcurl -plaintext localhost:8085 blockassembly_api.BlockAssemblyAPI.HealthGRPC && grpcurl -plaintext localhost:8088 blockvalidation_api.BlockValidationAPI.HealthGRPC
          #   initialDelaySeconds: 1
          #   periodSeconds: 10
          #   failureThreshold: 5
          #   timeoutSeconds: 3
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc
      - name: init-script
        configMap:
          name: postgres-init-scripts
