apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: profiler-ingressroute-tcp-9091
  labels:
    service: miner
spec:
  entryPoints:
    - prof
  routes:
    - match: HostSNI(`miner.allinone.ubsv.dev`)
      services:
        - name: miner
          port: 9091
