apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: status-ingress-9908
  labels:
    service: miner
spec:
  entryPoints:
    - status
  routes:
    - match: HostSNI(`*`)
      services:
        - name: miner
          port: 9908
