apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: status-ingress-tcp-9909
  labels:
    service: miner
spec:
  entryPoints:
    - status-grpc
  routes:
  - match: HostSNI(`*`)
    services:
    - name: miner
      port: 9909
