apiVersion: v1
kind: Service
metadata:
  name: tx-blaster-service
  namespace: miner
  labels:
    app: tx-blaster
  annotations:
    prometheus.io/port: "9092"
    prometheus.io/scrape: "true"
spec:
  clusterIP: None
  ipFamilyPolicy: SingleStack
  ipFamilies:
    - IPv4
  selector:
    app: tx-blaster
  ports:
    - name: profiler
      port: 9091
      targetPort: 9091
      protocol: TCP
    - name: tx-blaster-profiler
      port: 9092
      targetPort: 9092
      protocol: TCP
