apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: miner3-ingressroute-tcp-8084
  namespace: miner3
spec:
  entryPoints:
    - prop-grpc
  routes:
  - match: HostSNI(`miner3.ubsv.dev`)
    services:
    - name: miner3
      port: 8084
  tls:
    passthrough: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: miner3-ingressroute-tcp-8090
  namespace: miner3
spec:
  entryPoints:
    - blob-http
  routes:
  - match: HostSNI(`miner3.ubsv.dev`)
    services:
    - name: miner3
      port: 8090
  tls:
    # use miner3-cert
#    secretName: miner3-tls
    passthrough: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: miner3-ingressroute-tcp-8091
  namespace: miner3
spec:
  entryPoints:
    - blob-grpc
  routes:
  - match: HostSNI(`miner3.ubsv.dev`)
    services:
    - name: miner3
      port: 8091
  tls:
    # use miner3-cert
#    secretName: miner3-tls
    passthrough: true
