apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: miner1-ingressroute-tcp-8084
  namespace: miner1
spec:
  entryPoints:
    - prop-grpc
  routes:
  - match: HostSNI(`miner1.allinone.ubsv.dev`)
    services:
    - name: miner1
      port: 8084
  tls:
    passthrough: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: miner1-ingressroute-tcp-8090
  namespace: miner1
spec:
  entryPoints:
    - blob-http
  routes:
  - match: HostSNI(`miner1.allinone.ubsv.dev`)
    services:
    - name: miner1
      port: 8090
  tls:
    passthrough: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: miner1-ingressroute-tcp-8091
  namespace: miner1
spec:
  entryPoints:
    - blob-grpc
  routes:
  - match: HostSNI(`miner1.allinone.ubsv.dev`)
    services:
    - name: miner1
      port: 8091
  tls:
    # use miner1-cert
#    secretName: miner1-tls
    passthrough: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: bootstrap-ingressroute-http-8099
  namespace: miner1
spec:
  entryPoints:
    - bootstrap-http
  routes:
  - match: HostSNI(`bootstrap.allinone.ubsv.dev`)
    services:
    - name: miner1
      port: 8099
  tls:
    passthrough: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: bootstrap-ingressroute-grpc-8089
  namespace: miner1
spec:
  entryPoints:
    - bootstrap-grpc
  routes:
  - match: HostSNI(`bootstrap.allinone.ubsv.dev`)
    services:
    - name: miner1
      port: 8089
  tls:
    passthrough: true
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: m1-ingressroute-tcp-8093
  namespace: miner1
spec:
  entryPoints:
    - coin-grpc
  routes:
  - match: HostSNI(`coinbase.allinone.ubsv.dev`)
    services:
    - name: miner1
      port: 8093
  tls:
    passthrough: true
