apiVersion: v1
kind: PersistentVolume
metadata:
  name: propagation-luster-pv
spec:
  capacity:
    storage: 2400Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-033df9026a5888e36
    volumeAttributes:
      dnsname: fs-033df9026a5888e36.fsx.ap-south-1.amazonaws.com
      mountname: r5njtbmv


