apiVersion: v1
kind: PersistentVolume
metadata:
  name: blockpersister-lustre-pv
spec:
  capacity:
    storage: 1200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-0b0329368d8fa54f3
    volumeAttributes:
      dnsname: fs-0b0329368d8fa54f3.fsx.ap-south-1.amazonaws.com
      mountname: 5ztzbbmv
