apiVersion: v1
kind: PersistentVolume
metadata:
  name: subtree-lustre-pv
spec:
  capacity:
    storage: 2400Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-0edc846ca8e1a9745
    volumeAttributes:
      dnsname: fs-0edc846ca8e1a9745.fsx.ap-south-1.amazonaws.com
      mountname: kznjtbmv
