package settings

// AdaptiveFetchSettings controls the adaptive subtreeData fetch state
// machine used by blockvalidation and subtreevalidation. The state machine
// itself lives in pkg/adaptivefetch; see that package for the full
// transition truth table and bootstrap semantics.
type AdaptiveFetchSettings struct {
	BootstrapMode             string  `key:"adaptive_fetch_bootstrap_mode" desc:"Initial mode for the adaptive subtreeData fetch gate" default:"pessimistic" category:"AdaptiveFetch" usage:"pessimistic | optimistic | auto" type:"string" longdesc:"### Purpose\nControls whether the node starts fetching subtreeData files on startup or skips them.\n\n### Values\n- **pessimistic** (default) - Always fetch subtreeData. Safe for every deployment, including standalone nodes without a tx distributor.\n- **optimistic** - Skip subtreeData from the first block. Appropriate only when the node is served by a tx distributor that reliably delivers every transaction (e.g. dev-scale-1/2 at 1M TPS).\n- **auto** - Start pessimistic, then attempt Pess→Opt transition once the rolling window is satisfied. **Not safe by default today** — see MVP caveat below.\n\n### MVP measurement caveat (read before choosing auto)\nThe current MVP records synthetic observations in both modes: pessimistic-mode records LocalHits=TotalTxs (perfect locality) and optimistic-mode records MissingFetches=0 (no observed misses). Two consequences follow until real plumbing lands (see PR #745):\n\n- **Pess→Opt is effectively a warm-up gate, not a measurement.** With default WindowSize=10 and PessToOptHitRateThreshold=0.99, auto will transition to optimistic after 10 successful pessimistic blocks regardless of whether txs are genuinely local. Operators who do *not* run a tx distributor must keep bootstrap_mode=pessimistic — auto must not be used on non-distributor deployments today.\n- **Opt→Pess self-correction will not fire from observations.** The safety trips described in OptToPessMissThreshold / OptToPessAvgMissThreshold rely on a real MissingFetches count that this MVP does not plumb through. Recovery from a degraded distributor today relies on a node restart with bootstrap_mode=pessimistic.\n\n### Recommendations\n- **pessimistic** for mainnet / testnet / teratestnet today (this is the default)\n- **optimistic** for dev-scale 1M-TPS clusters where even one subtreeData download is too expensive\n- **auto** only on deployments backed by a reliable tx distributor, and only when you accept the warm-up-gate semantics described above"`
	WindowSize                int     `key:"adaptive_fetch_window_size" desc:"Rolling-window size used for mode transitions" default:"10" category:"AdaptiveFetch" usage:"Number of recent observations to average" type:"int"`
	PessToOptHitRateThreshold float64 `key:"adaptive_fetch_pess_to_opt_hit_rate_threshold" desc:"Min avg local-hit rate (0..1) to switch pessimistic → optimistic" default:"0.99" category:"AdaptiveFetch" usage:"0..1" type:"float64"`
	OptToPessMissThreshold    int     `key:"adaptive_fetch_opt_to_pess_miss_threshold" desc:"Absolute missing-tx count in a single block that immediately trips optimistic → pessimistic" default:"100" category:"AdaptiveFetch" usage:"Immediate safety trip" type:"int"`
	OptToPessAvgMissThreshold float64 `key:"adaptive_fetch_opt_to_pess_avg_miss_threshold" desc:"Avg missing-tx count over the window that trips optimistic → pessimistic" default:"10" category:"AdaptiveFetch" usage:"Rolling-average safety trip" type:"float64"`
}
