# dynamic provisioning for Lustre FSx for Lustre.
# take a look at pvs.yaml for understanding better why this is done this way
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blockpersister-lustre-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: blockpersister-lustre-pv-1
  resources:
    requests:
      storage: 1200Gi
