# dynamic provisioning for Lustre FSx for Lustre.
# take a look at pvs.yaml for understanding better why this is done this way. All others are statically provisioned
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subtree-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: "fsx-sc"
  resources:
    requests:
      storage: 1200Gi
