apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - bootstrap-deployment.yaml
  - bootstrap-http-ingress.yaml
  - bootstrap-grpc-ingress.yaml
  - bootstrap-configmap.yaml
  - bootstrap-service.yaml
  - service-account.yaml
