apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/allinone-miner

namespace: miner6

nameSuffix: "6"
commonLabels:
  app: miner6

configMapGenerator:
  - behavior: merge
    literals:
      - SETTINGS_CONTEXT=allinone.miner.6
    name: config-miner
  - behavior: merge
    literals:
      - SETTINGS_CONTEXT=allinone.coinbase.6
    name: coinbase-config


patches:
  - patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: HostSNI(`miner6.allinone.ubsv.dev`)
    target:
      kind: IngressRouteTCP
  - patch: |-
      - op: replace
        path: /spec/routes/0/services/0/name
        value: miner6
    target:
      kind: IngressRouteTCP
  - patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: miner6
    target:
      kind: ClusterRoleBinding
  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: sa-miner6
    target:
      kind: Deployment
