apiVersion: v1
kind: Service
metadata:
  name: aerospike
  namespace: gmp-public
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: aerospike
    - protocol: TCP
      port: 9145
      targetPort: 9145
      name: metrics
  selector:
    app: my-app
  externalName: aerospike-endpoint
---
apiVersion: v1
kind: Endpoints
metadata:
  name: aerospike-endpoint
  namespace: gmp-public
subsets:
  - addresses:
    - ip: 10.138.0.31
    ports:
    - port: 3000
      name: aerospike
    - port: 9145
      name: metrics
  - addresses:
    - ip: 10.138.0.30
    ports:
    - port: 3000
      name: aerospike
    - port: 9145
      name: metrics
  - addresses:
    - ip: 10.138.0.29
    ports:
    - port: 3000
      name: aerospike
    - port: 9145
      name: metrics
