apiVersion: v1
kind: Service
metadata:
  name: blockassembly-service
  namespace: blockassembly-service
  labels:
    app: blockassembly
    monitor: prometheus
spec:
  clusterIP: None
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
  selector:
    app: blockassembly
  ports:
    - name: tcp
      port: 8085
      targetPort: 8085
      protocol: TCP
    - name: profiler
      port: 9091
      targetPort: 9091
      protocol: TCP
