apiVersion: v1
kind: Service
metadata:
  name: kafka-tx-blaster-service
  namespace: tx-blaster-service
  labels:
    app: kafka-tx-blaster
    monitor: prometheus
spec:
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
  selector:
    app: kafka-tx-blaster
  ports:
    - name: tcp
      port: 8086
      targetPort: 8086
      protocol: TCP
    - name: profiler
      port: 9091
      targetPort: 9091
      protocol: TCP
