apiVersion: v1
kind: Service
metadata:
  name: validation-service
  namespace: aerospike-test
  labels:
    app: validation
    monitor: prometheus
spec:
  clusterIP: None
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
  selector:
    app: validation
  ports:
    - name: tcp
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: profiler
      port: 9091
      targetPort: 9091
      protocol: TCP
