apiVersion: apps/v1
kind: Deployment
metadata:
  name: blob
  namespace: blob-service
  labels:
    app: blob
    project: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blob
  template:
    metadata:
      labels:
        app: blob
    spec:
      serviceAccountName: s3-push-service-account
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: blob
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: blob
          image: 434394763103.dkr.ecr.eu-north-1.amazonaws.com/IMAGE:TAG
          args: [ "-blobserver=1" ]
          env:
            - name: SETTINGS_CONTEXT
              value: "kubernetes"
            - name: profilerAddr
              value: 0.0.0.0:9091
            - name: JAEGER_AGENT_HOST
              value: jaeger-cluster-agent.jaeger.svc.cluster.local
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: SERVICE_NAME
              value: blob-service
            - name: blockvalidation_grpcAddress
              value: "blockvalidation-service.blockvalidation-service.svc.cluster.local:8088"
            - name: blockchain_grpcAddress
              value: "blockchain-service.blockchain-service.svc.cluster.local:8087"
            - name: blobserver_httpAddress
              value: "https://blob-service.blob-service.svc.cluster.local:8090"
            - name: blobserver_clientName
              value: "M1"
            - name: blobserver_grpcAddress
              value: "blob-service.blob-service.svc.cluster.local:8091"
            - name: bootstrap_grpcAddress
              value: "bootstrap-service.bootstrap-service.svc.cluster.local:8089"
            - name: bootstrap_httpAddress
              value: "bootstrap-service.bootstrap-service.svc.cluster.local:8099"
            - name: txstore
              value: minio://minio:minio123@myminio-hl.minio.svc.cluster.local:9000/tx-lake
            - name: utxostore
              value: aerospike://utxo-store-0.ubsv.internal:3000/utxostore
          ports:
            - containerPort: 8090
              protocol: TCP
            - containerPort: 8099
              protocol: TCP
            - containerPort: 8091
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
            - containerPort: 4040
              protocol: TCP
          resources:
            requests:
              memory: 1Gi
              cpu: "2"
            limits:
              memory: 2Gi
              cpu: "2"
          readinessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
