apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain
  namespace: blockchain-service
  labels:
    app: blockchain
    project: service
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: blockchain
  template:
    metadata:
      labels:
        app: blockchain
    spec:
      serviceAccountName: s3-push-service-account
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: blockchain
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: blockchain
          image: 434394763103.dkr.ecr.eu-north-1.amazonaws.com/IMAGE:TAG
          args: [ "-blockchain=1", "-seeder=1" ] # todo joe fix we need blockchain to be blocking
          env:
            - name: SETTINGS_CONTEXT
              value: "kubernetes"
            - name: profilerAddr
              value: 0.0.0.0:9091
            - name: JAEGER_AGENT_HOST
              value: jaeger-cluster-agent.jaeger.svc.cluster.local
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: SERVICE_NAME
              value: blockchain-service
            - name: blockchain_store
              value: postgres://m1:m1@services-db.cipebxcxpkpk.eu-north-1.rds.amazonaws.com:5432/m1
            - name: txmeta_store
              value: aerospike://tx-status-store-0.ubsv.internal:3000/txstatus_store
            - name: utxostore
              value: aerospike://utxo-store-0.ubsv.internal:3000/utxostore
          ports:
            - containerPort: 8081
              protocol: TCP
            - containerPort: 8087
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
            - containerPort: 4040
              protocol: TCP
          resources:
            requests:
              memory: 2Gi
              cpu: "2"
            limits:
              memory: 2Gi
              cpu: "2"
          readinessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
