apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: blockassembly
    monitor: prometheus
  name: blockassembly
  namespace: aerospike-test
spec:
  selector:
    matchLabels:
      app: blockassembly
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: blockassembly
        monitor: prometheus
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: blockassembly
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - args:
        - -blockassembly=1
        env:
        - name: SETTINGS_CONTEXT
          value: kubernetes
        - name: blockassembly_grpcAddress
          value: 0.0.0.0:8085
        - name: utxostore
          value: aerospike://10.138.0.29:3000/test
        - name: profilerAddr
          value: 0.0.0.0:9091
        - name: JAEGER_AGENT_HOST
          value: jaeger-cluster-agent.jaeger.svc.cluster.local
        - name: JAEGER_AGENT_PORT
          value: "6831"
        - name: SERVICE_NAME
          value: blockassembly-service
        image: eu.gcr.io/PROJECT/IMAGE:TAG
        imagePullPolicy: IfNotPresent
        name: blockassembly
        ports:
        - containerPort: 8055
          protocol: TCP
        - containerPort: 9091
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 2Gi
          requests:
            cpu: "1"
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
