apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockassembly
  namespace: blockassembly-service
  labels:
    monitor: prometheus
    app: blockassembly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockassembly
  template:
    metadata:
      labels:
        app: blockassembly
        monitor: prometheus
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: blockassembly
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: blockassembly
          image: 434394763103.dkr.ecr.eu-north-1.amazonaws.com/IMAGE:TAG
          args: ["-blockassembly=1"]
          env:
          - name: SETTINGS_CONTEXT
            value: "kubernetes"
          - name: blockassembly_grpcAddress
            value: 0.0.0.0:8085
          - name: utxostore
            # value: aerospike://192.168.13.144:3000/test
            value: memory://utxostore-service.utxostore-service.svc.cluster.local:8082
          - name: profilerAddr
            value: 0.0.0.0:9091
          - name: JAEGER_AGENT_HOST
            value: jaeger-cluster-agent.jaeger.svc.cluster.local
          - name: JAEGER_AGENT_PORT
            value: "6831"
          - name: SERVICE_NAME
            value: blockassembly-service
          ports:
            - containerPort: 8055git config --global commit.gpgsign false
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
          resources:
            requests:
              memory: 1Gi
              cpu: "1"
            limits:
              memory: 2Gi
              cpu: "1"
