apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockassembly
  namespace: blockassembly-service
  labels:
    app: blockassembly
    project: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockassembly
  template:
    metadata:
      labels:
        app: blockassembly
    spec:
      serviceAccountName: s3-push-service-account
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: blockassembly
                topologyKey: "kubernetes.io/hostname"
      tolerations:
        - key: service
          value: blockassembly
          operator: Equal
          effect: NoSchedule
      containers:
        - name: blockassembly
          image: 434394763103.dkr.ecr.eu-north-1.amazonaws.com/IMAGE:TAG
          args: [ "-blockassembly=1" ]
          env:
            - name: SETTINGS_CONTEXT
              value: "kubernetes"
            - name: blockassembly_grpcListenAddress
              value: :8085
            - name: utxostore
              value: aerospike://utxo-store-0.ubsv.internal:3000/utxostore
            #            value: memory://utxostore-service.utxostore-service.svc.cluster.local:8082
            - name: blockchain_grpcAddress
              value: blockchain-service.blockchain-service.svc.cluster.local:8087
            - name: txmeta_store
              value: aerospike://tx-status-store-0.ubsv.internal:3000/txstatus_store
            - name: profilerAddr
              value: 0.0.0.0:9091
            - name: JAEGER_AGENT_HOST
              value: jaeger-cluster-agent.jaeger.svc.cluster.local
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: SERVICE_NAME
              value: blockassembly-service
            - name: subtreestore
#              value: minio://minio:minio123@myminio-hl.minio.svc.cluster.local:9000/block-lake
              value: s3:///ubsv-subtree-store?region=eu-north-1 # todo separate the data later
          ports:
            - containerPort: 8055
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
          resources:
            requests:
              memory: 10Gi
              cpu: "1"
            limits:
              memory: 10Gi
              cpu: "1"
          readinessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
