apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinbase
  namespace: coinbase-service
  labels:
    app: coinbase
    project: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coinbase
  template:
    metadata:
      labels:
        app: coinbase
    spec:
      serviceAccountName: s3-push-service-account
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: coinbase
                topologyKey: "kubernetes.io/hostname"
      tolerations:
        - key: service
          value: coinbase
          operator: Equal
          effect: NoSchedule
      containers:
        - name: coinbase
          image: 434394763103.dkr.ecr.eu-north-1.amazonaws.com/IMAGE:TAG
          args: [ "-coinbase=1" ]
          env:
            - name: SETTINGS_CONTEXT
              value: "kubernetes"
            - name: coinbase_grpcAddress
              value: :8093
            - name: blobserver_grpcAddress
              value: "miner3.miner3.svc.cluster.local:8091"
            - name: coinbase_store
              value: postgres://coinbase:coinbase@services-db.cipebxcxpkpk.eu-north-1.rds.amazonaws.com:5432/coinbase
            - name: profilerAddr
              value: 0.0.0.0:9091
            - name: logLevel
              value: DEBUG
            - name: JAEGER_AGENT_HOST
              value: jaeger-cluster-agent.jaeger.svc.cluster.local
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: SERVICE_NAME
              value: coinbase-service
          ports:
            - containerPort: 8093
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
          resources:
            requests:
              memory: 1Gi
              cpu: "0.5"
            limits:
              memory: 1Gi
              cpu: "0.5"
          readinessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
        - name: postgres-sidecar
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "really_strong_password_change_me"
            - name: POSTGRES_DB
              value: "miner_coinbase"
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: 1Gi
              cpu: "0.5"
            limits:
              memory: 2Gi
              cpu: "1"
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
