apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-tx-blaster
  namespace: tx-blaster-service
  labels:
    monitor: prometheus
    app: kafka-tx-blaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-tx-blaster
  template:
    metadata:
      labels:
        app: kafka-tx-blaster
        monitor: prometheus
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: kafka-tx-blaster
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: kafka-tx-blaster
          image: eu.gcr.io/PROJECT/IMAGE:TAG
          command:
            - ./blaster.run
          args: ["-workers=1000", "-print=10000", "-kafka=kafka://kafka-cluster-headless.kafka.svc.cluster.local:9092/txs"]
          env:
            - name: SETTINGS_CONTEXT
              value: "kubernetes"
            - name: propagation_grpcAddress
              value: k8s:///propagation-service.propagation-service.svc.cluster.local:8084
            - name: seeder_grpcAddress
              value: k8s:///seeder-service.seeder-service.svc.cluster.local:8083
            - name: profilerAddr
              value: 0.0.0.0:9091
            - name: tx_blaster_profilerAddr
              value: 0.0.0.0:9091
            - name: JAEGER_AGENT_HOST
              value: jaeger-cluster-agent.jaeger.svc.cluster.local
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: SERVICE_NAME
              value: kafka-tx-blaster-service
            - name: number_of_outputs
              value: "5000"
          ports:
            - containerPort: 8086
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
            - containerPort: 4040
              protocol: TCP
          resources:
            requests:
              memory: 1Gi
              cpu: "1"
            limits:
              memory: 2Gi
              cpu: "1"
