apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - propagation.yaml
  - validation.yaml
  - tx-blaster.yaml
  - blockassembly.yaml
  - seeder.yaml
  - utxostore.yaml
  - miner1.yaml
  - miner2.yaml
  - miner3.yaml
