apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - propagation.yaml
  - validation.yaml
  - tx-blaster.yaml
  - blockassembly.yaml
  - utxostore.yaml
  - miner1.yaml
  - miner2.yaml
  - miner3.yaml
  - coinbase.yaml
  - blob.yaml
  - blockvalidation.yaml
  - blockchain.yaml
  - bootstrap.yaml
  - bootstrap-deployment.yaml
  - tx-blaster-allinone-miner.yaml
  - bootstrap-allinone-miner.yaml
