apiVersion: apps/v1
kind: Deployment
metadata:
  name: miner3
  namespace: miner3
  labels:
    app: miner3
    project: miner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miner3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: miner3
    spec:
      serviceAccountName: s3-push-service-account
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: miner3
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: miner
          image: 434394763103.dkr.ecr.eu-north-1.amazonaws.com/IMAGE:TAG
          args: [ "-coinbase=0" ]
          env:
            - name: SETTINGS_CONTEXT
              value: allinone.miner.3
            - name: utxostore
              value: postgres://miner3:miner3@services-db.cipebxcxpkpk.eu-north-1.rds.amazonaws.com:5432/ubsv3
            - name: txmeta_store
              value: postgres://miner3:miner3@services-db.cipebxcxpkpk.eu-north-1.rds.amazonaws.com:5432/ubsv3
            - name: blockchain_store
              value: postgres://miner3:miner3@services-db.cipebxcxpkpk.eu-north-1.rds.amazonaws.com:5432/ubsv3
            - name: txstore
              value: minio://minio:minio123@myminio-hl.minio.svc.cluster.local:9000/tx-lake?objectLocking=true
            - name: subtreestore
              value: minio://minio:minio123@myminio-hl.minio.svc.cluster.local:9000/subtrees-lake?objectLocking=true&tempTTL=true
            - name: startTxMetaStore
              value: "false"
            - name: startUtxoStore
              value: "false"
            - name: blobserver_grpcListenAddress
              value: ":8091"
            - name: blockassembly_grpcAddress
              value: ":8085"
            - name: blobserver_httpAddress
              value: "https://miner3.miner3.svc.cluster.local:8090"
            - name: blobserver_grpcAddress
              value: "miner3.miner3.svc.cluster.local:8091"
            - name: blobserver_clientName
              value: "Miner 3"
            - name: bootstrap_grpcAddress
              value: "miner1.miner1.svc.cluster.local:8089"
            - name: bootstrap_httpAddress
              value: "miner1.miner1.svc.cluster.local:8099"
            - name: startBootstrapServer
              value: "false"
            - name: blobserver_httpListenAddress
              value: ":8090"
            - name: blockassembly_grpcListenAddress
              value: ":8085"
            - name: blockchain_grpcListenAddress
              value: ":8087"
            - name: blockvalidation_grpcListenAddress
              value: ":8088"
            - name: gocore_stats_addr
              value: ":9092"
            - name: propagation_grpcListenAddress
              value: ":8084"
            - name: txmeta_grpcListenAddress
              value: ":8086"
            - name: validator_grpcListenAddress
              value: ":8081"
            - name: seeder_grpcListenAddress
              value: ":8083"
            - name: JAEGER_AGENT_HOST
              value: jaeger-cluster-agent.jaeger.svc.cluster.local
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: profilerAddr
              value: 0.0.0.0:9091
            - name: SERVICE_NAME
              value: miner3
          ports:
            - containerPort: 8082
              protocol: TCP
            - containerPort: 8083
              protocol: TCP
            - containerPort: 8084
              protocol: TCP
            - containerPort: 8090
              protocol: TCP
            - containerPort: 8091
              protocol: TCP
            - containerPort: 8092
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
            - containerPort: 4040
              protocol: TCP
          resources:
            requests:
              memory: 10Gi
              cpu: "1"
            limits:
              memory: 10Gi
              cpu: "1"
          readinessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
        - name: postgres-sidecar
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "really_strong_password_change_me"
            - name: POSTGRES_DB
              value: "miner_coinbase"
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: 1Gi
              cpu: "0.5"
            limits:
              memory: 2Gi
              cpu: "1"
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
