apiVersion: apps/v1
kind: Deployment
metadata:
  name: miner1
  namespace: miner1
  labels:
    app: miner1
    project: miner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miner1
  template:
    metadata:
      labels:
        app: miner1
    spec:
      serviceAccountName: s3-push-service-account
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: miner1
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: miner
          image: 434394763103.dkr.ecr.eu-north-1.amazonaws.com/IMAGE:TAG
          command: ["./dlv", "--listen=:4040", "--continue", "--accept-multiclient", "--headless=true", "--api-version=2", "exec", "./ubsv.run", "--"]
          args: [ "-coinbase=0" ]
          env:
            - name: utxostore # todo joe to create a better postgres db
              value: postgres://miner1:miner1@services-db.cipebxcxpkpk.eu-north-1.rds.amazonaws.com:5432/ubsv1
            - name: txmeta_store
              value: postgres://miner1:miner1@services-db.cipebxcxpkpk.eu-north-1.rds.amazonaws.com:5432/ubsv1
            - name: blockchain_store
              value: postgres://miner1:miner1@services-db.cipebxcxpkpk.eu-north-1.rds.amazonaws.com:5432/ubsv1
            - name: txstore # todo change bucket txstore
              value: s3:///ubsv-utxo-store?region=eu-north-1 # todo separate the data later
            - name: subtreestore
              value: s3:///ubsv-subtree-store?region=eu-north-1 # todo separate the data later
            - name: coinbasetracker_grpcAddress
              value: "coinbase-service.coinbase-service.svc.cluster.local:8093"
            - name: startTxMetaStore
              value: "false"
            - name: startUtxoStore
              value: "false"
            - name: blobserver_grpcAddress
              value: ":8091"
            - name: blobserver_remoteAddress
              value: "miner1.miner1.svc.cluster.local:8091"
            - name: blobserver_remoteAddresses
              value: "miner2.miner2.svc.cluster.local:8091|miner3.miner3.svc.cluster.local:8091"
            - name: blobserver_baseURL
              value: "http://miner1.miner1.svc.cluster.local:8090"
            - name: startBootstrapServer
              value: "false"
            - name: blobserver_httpAddress
              value: ":8090"
            - name: blockassembly_grpcAddress
              value: ":8085"
            - name: blockchain_grpcAddress
              value: ":8087"
            - name: blockvalidation_grpcAddress
              value: ":8088"
            - name: gocore_stats_addr
              value: ":9092"
            - name: propagation_grpcAddress
              value: ":8084"
            - name: txmeta_grpcAddress
              value: ":8086"
            - name: validator_grpcAddress
              value: ":8081"
            - name: seeder_grpcAddress
              value: ":8083"
            - name: SETTINGS_CONTEXT
              value: "dev"
            - name: JAEGER_AGENT_HOST
              value: jaeger-cluster-agent.jaeger.svc.cluster.local
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: profilerAddr
              value: 0.0.0.0:9091
            - name: SERVICE_NAME
              value: miner1
          ports:
            - containerPort: 8082
              protocol: TCP
            - containerPort: 8083
              protocol: TCP
            - containerPort: 8084
              protocol: TCP
            - containerPort: 8090
              protocol: TCP
            - containerPort: 8091
              protocol: TCP
            - containerPort: 8092
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
          resources:
            requests:
              memory: 12Gi
              cpu: "6"
            limits:
              memory: 12Gi
              cpu: "6"
          readinessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
        - name: postgres-sidecar
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "really_strong_password_change_me"
            - name: POSTGRES_DB
              value: "miner_coinbase"
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: 1Gi
              cpu: "0.5"
            limits:
              memory: 2Gi
              cpu: "1"
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
