apiVersion: apps/v1
kind: Deployment
metadata:
  name: miner2
  namespace: miner2
  labels:
    app: miner2
    project: miner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miner2
  template:
    metadata:
      labels:
        app: miner2
    spec:
      serviceAccountName: s3-push-service-account
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: miner2
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: miner2
          image: 434394763103.dkr.ecr.eu-north-1.amazonaws.com/IMAGE:TAG
          env:
            - name: blobserver_grpcAddress
              value: ":8091"
            - name: blobserver_remoteAddress
              value: "miner2.miner2.svc.cluster.local:8091"
            - name: blobserver_baseURL
              value: "http://miner2.miner2.svc.cluster.local:8090"
            - name: startBootstrapServer
              value: "false"
            - name: bootstrap_grpcAddress
              value: "bootstrap-service.bootstrap-service.svc.cluster.local:8089"
            - name: blobserver_httpAddress
              value: ":8090"
            - name: blockassembly_grpcAddress
              value: ":8085"
            - name: blockchain_grpcAddress
              value: ":8087"
            - name: blockvalidation_grpcAddress
              value: ":8088"
            - name: gocore_stats_addr
              value: ":9092"
            - name: propagation_grpcAddress
              value: ":8084"
            - name: txmeta_grpcAddress
              value: ":8086"
            - name: validator_grpcAddress
              value: ":8081"
            - name: seeder_grpcAddress
              value: ":8083"
            - name: SETTINGS_CONTEXT
              value: "dev"
            - name: JAEGER_AGENT_HOST
              value: jaeger-cluster-agent.jaeger.svc.cluster.local
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: profilerAddr
              value: 0.0.0.0:9091
            - name: SERVICE_NAME
              value: miner2
          ports:
            - containerPort: 8082
              protocol: TCP
            - containerPort: 8083
              protocol: TCP
            - containerPort: 8084
              protocol: TCP
            - containerPort: 8090
              protocol: TCP
            - containerPort: 8091
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
          resources:
            requests:
              memory: 12Gi
              cpu: "6"
            limits:
              memory: 12Gi
              cpu: "6"
          readinessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
