apiVersion: apps/v1
kind: Deployment
metadata:
  name: miner1
  namespace: miner1
  labels:
    app: miner1
    project: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miner1
  template:
    metadata:
      labels:
        app: miner1
    spec:
      serviceAccountName: s3-push-service-account
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: miner1
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: miner1
          image: 434394763103.dkr.ecr.eu-north-1.amazonaws.com/IMAGE:TAG
          args: [ "-utxostore=1", "-blockassembly=1", "-propagation=1", "-seeder=1", "-validator=1", "-blockvalidation=1", "-blockvalidation=1", "-blockchain=1", "-txmeta=1", "-blobserver=1" ]
          env:
            - name: SETTINGS_CONTEXT
              value: "dev"
            - name: JAEGER_AGENT_HOST
              value: jaeger-cluster-agent.jaeger.svc.cluster.local
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: profilerAddr
              value: 0.0.0.0:9091
            - name: SERVICE_NAME
              value: miner1
          ports:
            - containerPort: 8082
              protocol: TCP
            - containerPort: 8083
              protocol: TCP
            - containerPort: 8084
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
          resources:
            requests:
              memory: 12Gi
              cpu: "6"
            limits:
              memory: 12Gi
              cpu: "6"
          readinessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tx-blaster-miner1
  namespace: miner1
  labels:
    app: tx-blaster-miner1
    project: service
spec:
  replicas: 0
  selector:
    matchLabels:
      app: tx-blaster-miner1
  template:
    metadata:
      labels:
        app: tx-blaster-miner1
    spec:
      serviceAccountName: s3-push-service-account
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: tx-blaster-miner1
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: miner1
          image: 434394763103.dkr.ecr.eu-north-1.amazonaws.com/IMAGE:TAG
          command:
            - ./blaster.run
          args: [ "-workers=1", "-print=100" ]
          env:
            - name: SETTINGS_CONTEXT
              value: "dev"
            - name: number_of_outputs
              value: "5000"
            - name: use_cgo_signer
              value: "true"
            - name: JAEGER_AGENT_HOST
              value: jaeger-cluster-agent.jaeger.svc.cluster.local
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: profilerAddr
              value: 0.0.0.0:9091
            - name: SERVICE_NAME
              value: tx-blaster-miner1
            - name: propagation_grpcAddress
              value: k8s:///miner1.miner1.svc.cluster.local:8084
            - name: seeder_grpcAddress
              value: k8s:///miner1.miner1.svc.cluster.local:8083
          ports:
            - containerPort: 9091
              protocol: TCP
          resources:
            requests:
              memory: 8Gi
              cpu: "2"
            limits:
              memory: 8Gi
              cpu: "2"
          readinessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3