# service-account for s3 upload
apiVersion: v1
kind: ServiceAccount
metadata:
  name: s3-push-service-account
  namespace: propagation-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::434394763103:role/eks-s3-role-pusher
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: propagation
  namespace: propagation-service
  labels:
    app: propagation
spec:
  replicas: 0
  selector:
    matchLabels:
      app: propagation
  template:
    metadata:
      labels:
        app: propagation
    spec:
      serviceAccountName: s3-push-service-account
      volumes:
        - name: secret-volume
          secret:
            secretName: utxo-writer-gcs-sa
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: propagation
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: propagation
          image: 434394763103.dkr.ecr.eu-north-1.amazonaws.com/IMAGE:TAG
          args: ["-propagation=1"]
          # command: "You can override the entrypoint with a command."
          #command: ["./dlv", "--listen=:4040", "--continue", "--accept-multiclient", "--headless=true", "--api-version=2", "exec", "./ubsv.run", "--"]
#          command: [ "./ubsv.run" ]
          env:
            - name: SETTINGS_CONTEXT
              value: "kubernetes"
            - name: validator_grpcAddress
              value: k8s:///validation-service.validation-service.svc.cluster.local:8081
            - name: profilerAddr
              value: 0.0.0.0:9091
            - name: JAEGER_AGENT_HOST
              value: jaeger-cluster-agent.jaeger.svc.cluster.local
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: SERVICE_NAME
              value: propagation-service
            - name: txstore
              value: s3://ubsv-utxo-store?region=eu-north-1
          ports:
            - containerPort: 8833
              protocol: TCP
            - containerPort: 4040
              protocol: TCP
          volumeMounts:
            - name: secret-volume
              mountPath: /app/keyfile.json
              readOnly: true
              subPath: utxo-writer-ubsv-383015-84d57e41cdda.json
          resources:
            requests:
              memory: 4Gi
              cpu: "2"
            limits:
              memory: 8Gi
              cpu: "2"
