apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: propagation
    monitor: prometheus
  name: propagation
  namespace: aerospike-test
spec:
  selector:
    matchLabels:
      app: propagation
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: propagation
        monitor: prometheus
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchLabels:
                  app: propagation
              topologyKey: kubernetes.io/hostname
            weight: 100
      containers:
      - args:
        - -propagation=1
        command:
        - ./ubsv.run
        env:
        - name: SETTINGS_CONTEXT
          value: kubernetes
        - name: regtestSync
          value: "0"
        - name: txstore
          value: badger:///data/txstore
        - name: blockstore
          value: badger:///data/blockstore
        - name: validator_grpcAddress
          value: k8s:///validation-service.aerospike-test.svc.cluster.local:8081
        - name: profilerAddr
          value: 0.0.0.0:9091
        - name: JAEGER_AGENT_HOST
          value: jaeger-cluster-agent.jaeger.svc.cluster.local
        - name: JAEGER_AGENT_PORT
          value: "6831"
        - name: SERVICE_NAME
          value: propagation-service
        image: 434394763103.dkr.ecr.eu-north-1.amazonaws.com/IMAGE:TAG
        imagePullPolicy: IfNotPresent
        name: propagation
        ports:
        - containerPort: 8833
          protocol: TCP
        - containerPort: 4040
          protocol: TCP
        resources:
          limits:
            cpu: "2"
            memory: 8Gi
          requests:
            cpu: "2"
            memory: 4Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
