apiVersion: apps/v1
kind: Deployment
metadata:
  name: utxostore
  namespace: utxostore-service
  labels:
    app: utxostore
    project: service
spec:
  replicas: 0
  selector:
    matchLabels:
      app: utxostore
  template:
    metadata:
      labels:
        app: utxostore
    spec:
      containers:
        - name: utxostore
          image: 434394763103.dkr.ecr.eu-north-1.amazonaws.com/IMAGE:TAG
          args: [ "-utxostore=1" ]
          env:
            - name: SETTINGS_CONTEXT
              value: "kubernetes"
            - name: utxostore
              #value: memory://:8082
              value: memory://:8082/splitbyhash
            - name: JAEGER_AGENT_HOST
              value: jaeger-cluster-agent.jaeger.svc.cluster.local
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: profilerAddr
              value: 0.0.0.0:9091
            - name: SERVICE_NAME
              value: utxostore-mem
          ports:
            - containerPort: 8082
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
          resources:
            requests:
              memory: 1Gi
              cpu: "20"
            limits:
              memory: 8Gi
              cpu: "20"
