apiVersion: apps/v1
kind: Deployment
metadata:
  name: utxostore
  namespace: utxostore-service
  labels:
    app: utxostore
    project: service
spec:
  replicas: 0
  selector:
    matchLabels:
      app: utxostore
  template:
    metadata:
      labels:
        app: utxostore
    spec:
      containers:
        - name: utxostore
          image: 434394763103.dkr.ecr.eu-north-1.amazonaws.com/IMAGE:TAG
          args: []
          env:
            - name: SETTINGS_CONTEXT
              value: scaling.m1
            - name: JAEGER_AGENT_HOST
              value: jaeger-cluster-agent.jaeger.svc.cluster.local
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: SERVICE_NAME
              value: miner1
            # Remove the following lines to revert to aerospike as defined in setting_local.conf
            - name: utxostore
              value: memory://:8082
            - name: startUtxoStore
              value: "true"
          ports:
            - containerPort: 8089
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
          resources:
            requests:
              memory: 1Gi
              cpu: "20"
            limits:
              memory: 8Gi
              cpu: "20"
