apiVersion: apps/v1
kind: Deployment
metadata:
  name: validation
  namespace: validation-service
  labels:
    app: validation
spec:
  replicas: 0
  selector:
    matchLabels:
      app: validation
  template:
    metadata:
      labels:
        app: validation
    spec:
      serviceAccountName: s3-push-service-account
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: validation
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: validation
          image: 434394763103.dkr.ecr.eu-north-1.amazonaws.com/IMAGE:TAG
          args: ["-validator=1"]
          env:
          - name: SETTINGS_CONTEXT
            value: "kubernetes"
          - name: utxostore
            value: aerospike://utxo-store-0.ubsv.internal:3000/utxostore
          - name: txstatus_store
            value: aerospike://tx-status-store-0.ubsv.internal:3000/txstatus_store
#            value: memory://utxostore-service.utxostore-service.svc.cluster.local:8082
            #value: foundationdb://foundationdb-exporter-service:9444
          - name: validator_grpcAddress
            value: 0.0.0.0:8081
          - name: blockassembly_grpcAddress
            value: k8s:///blockassembly-service.blockassembly-service.svc.cluster.local:8085
          - name: profilerAddr
            value: 0.0.0.0:9091
          - name: JAEGER_AGENT_HOST
            value: jaeger-cluster-agent.jaeger.svc.cluster.local
          - name: JAEGER_AGENT_PORT
            value: "6831"
          - name: SERVICE_NAME
            value: validation-service
          - name: use_cgo_verifier
            value: "true"
          - name: txstore
            value: s3://ubsv-utxo-store?region=eu-north-1
          ports:
            - containerPort: 8081
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
            - containerPort: 4040
              protocol: TCP
          resources:
            requests:
              memory: 1Gi
              cpu: "2"
            limits:
              memory: 2Gi
              cpu: "2"
