apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinbasetracker
  namespace: coinbasetracker-service
  labels:
    app: coinbasetracker
    project: service
spec:
  replicas: 0
  selector:
    matchLabels:
      app: coinbasetracker
  template:
    metadata:
      labels:
        app: coinbasetracker
    spec:
      serviceAccountName: s3-push-service-account
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: coinbasetracker
                topologyKey: "kubernetes.io/hostname"
      tolerations:
        - key: service
          value: coinbasetracker
          operator: Equal
          effect: NoSchedule
      containers:
        - name: postgres-sidecar
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "really_strong_password_change_me"
            - name: POSTGRES_DB
              value: "miner_coinbase"
          ports:
            - containerPort: 5432
          resources:
            requests:
              memory: 1Gi
              cpu: "0.5"
            limits:
              memory: 2Gi
              cpu: "1"
          readinessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
          livenessProbe:
            tcpSocket:
              port: 5432
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
        - name: coinbasetracker
          image: 434394763103.dkr.ecr.eu-north-1.amazonaws.com/IMAGE:TAG
          args: [ "-coinbasetracker=1" ]
          env:
            - name: SETTINGS_CONTEXT
              value: "kubernetes"
            - name: coinbasetracker_grpcAddress
              value: 0.0.0.0:8092
            - name: profilerAddr
              value: 0.0.0.0:9091
            - name: JAEGER_AGENT_HOST
              value: jaeger-cluster-agent.jaeger.svc.cluster.local
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: SERVICE_NAME
              value: coinbasetracker-service
          ports:
            - containerPort: 8092
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
          resources:
            requests:
              memory: 1Gi
              cpu: "0.5"
            limits:
              memory: 1Gi
              cpu: "0.5"
          readinessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
