apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - cloudflare-config-map.yaml
  - cloudflare.yaml
  - nginx-config-map.yaml
  - nginx-status-map.yaml
  - nginx-service.yaml
  - nginx.yaml
