apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    events {
      worker_connections  1024;
    }

    http {
      # Server configuration
      server {
        listen 80 default_server;
        
        # Specifying a resolver is a workaround for a bug in nginx
        # where it will not start if it cannot resolve any hostname
        # that's is used in the configuration file.
        resolver kube-dns.kube-system.svc.cluster.local valid=5s;

        location /p2p-ws {
          set $p2p p2p-service1.m1.svc.cluster.local:9906;
          proxy_pass http://$p2p;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }

        location ~ ^/(health|gocore) {
            return 403;
        }

        location / {
          set $asset asset-service1.m1.svc.cluster.local:8090;
          proxy_pass http://$asset;
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          # proxy_set_header Host $host;
          proxy_set_header Host "m1.scaling.ubsv.dev";
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
          proxy_buffering  on;
        }
      }
    }
