apiVersion: v1
kind: PersistentVolume
metadata:
  name: subtree-lustre-pv
spec:
  capacity:
    storage: 2400Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-0dba493d5571362d0
    volumeAttributes:
      dnsname: fs-0dba493d5571362d0.fsx.ap-northeast-2.amazonaws.com
      mountname: r57mnbmv
