apiVersion: v1
kind: PersistentVolume
metadata:
  name: blockpersister-lustre-pv
spec:
  capacity:
    storage: 1200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-0d2f578e122722056
    volumeAttributes:
      dnsname: fs-0d2f578e122722056.fsx.us-west-2.amazonaws.com
      mountname: ymfilbev
