apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/scaling-miner

namespace: m1

commonLabels:
  app: m1

configMapGenerator:
  - behavior: merge
    literals:
      - SETTINGS_CONTEXT=scaling.m1
    name: config-miner


patches:
  - patch: |-
      - op: replace
        path: /spec/routes/0/match
        value: HostSNI(`m1.scaling.ubsv.dev`)
    target:
      kind: IngressRouteTCP
  - patch: |-
      - op: replace
        path: /spec/routes/0/services/0/name
        value: m1
    target:
      kind: IngressRouteTCP
