apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subtree-pvc-t3
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: fsx-sc
  volumeName: subtree-lustre-pv-t3
  resources:
    requests:
      storage: 1200Gi
