apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: subtree-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: subtree-lustre-pv-2
  resources:
    requests:
      storage: 1200Gi
