apiVersion: v1
kind: PersistentVolume
metadata:
  name: blockpersister-lustre-pv
spec:
  capacity:
    storage: 1200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-0589f7e8ae8ec1994
    volumeAttributes:
      dnsname: fs-0589f7e8ae8ec1994.fsx.eu-central-1.amazonaws.com
      mountname: pbysxbev
