apiVersion: v1
kind: PersistentVolume
metadata:
  name: subtree-lustre-pv
spec:
  capacity:
    storage: 1200Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-0e423baefcbab9620
    volumeAttributes:
      dnsname: fs-0e423baefcbab9620.fsx.us-east-1.amazonaws.com
      mountname: dv3rlb4v
