apiVersion: v1
kind: PersistentVolume
metadata:
  name: propagation-luster-pv
spec:
  capacity:
    storage: 2400Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  persistentVolumeReclaimPolicy: Recycle
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-038627b1b48e7eab3
    volumeAttributes:
      dnsname: fs-038627b1b48e7eab3.fsx.us-east-1.amazonaws.com
      mountname: eklthb4v
