apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/allinone-miner

namespace: miner1

nameSuffix: "1"
commonLabels:
  app: miner1

configMapGenerator:
  - behavior: merge
    literals:
      - JAEGER_AGENT_HOST=jaeger-eu-west-1-agent.jaeger.svc.cluster.local
    name: config-miner
  - behavior: merge
    literals:
      - JAEGER_AGENT_HOST=jaeger-eu-west-1-agent.jaeger.svc.cluster.local
    name: tx-blaster-config
  - behavior: merge
    literals:
      - SETTINGS_CONTEXT=allinone.miner.1
    name: config-miner
  - behavior: merge
    literals:
      - SETTINGS_CONTEXT=allinone.miner.1
    name: tx-blaster-config
  - behavior: merge
    literals:
      - coinbase_grpcAddress=miner1.miner1.svc.cluster.local:8093
    name: tx-blaster-config

patches:
  - patch: |-
      - op: replace
        path: /spec/routes/0/services/0/name
        value: miner1
    target:
      kind: IngressRouteTCP
      labelSelector: service=miner
  - patch: |-
      - op: replace
        path: /spec/routes/0/services/0/name
        value: miner-service1
      - op: replace
        path: /spec/routes/0/match
        value: Host(`miner1.allinone.ubsv.dev`)
    target:
      kind: IngressRoute
      labelSelector: service=miner
  - patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: miner1
    target:
      kind: ClusterRoleBinding
  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: sa-miner1
    target:
      kind: Deployment
