apiVersion: teranode.bsvblockchain.org/v1alpha1
kind: Cluster
metadata:
  labels:
    app.kubernetes.io/created-by: teranode-operator
    app.kubernetes.io/instance: cluster
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cluster
    app.kubernetes.io/part-of: teranode-operator
    k8slens-edit-resource-version: v1alpha1
  name: mainnet-1
  namespace: mainnet-1
spec:
  asset:
    enabled: true
    spec:
      deploymentOverrides:
        nodeSelector:
          role: mainnet-1
        replicas: 1
        resources:
          requests:
            cpu: "0.6"
            memory: 500Mi
        tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: mainnet-1
      grpcIngress:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: ast-grpc
        className: traefik-internal
        host: euw1-teranode-main-net-1-prod.ubsv.dev
      httpIngress:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: web
        className: traefik-internal
        host: euw1-teranode-main-net-1-prod.ubsv.dev
      httpsIngress:
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt-prod
          traefik.ingress.kubernetes.io/router.entrypoints: websecure
        className: traefik-internal
        host: euw1-teranode-main-net-1-prod.ubsv.dev
  blockAssembly:
    enabled: true
    spec:
      deploymentOverrides:
        nodeSelector:
          role: mainnet-1
        replicas: 1
        resources:
          requests:
            cpu: "0.5"
            memory: 4Gi
        tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: mainnet-1
  blockPersister:
    enabled: false
    spec:
      deploymentOverrides:
        nodeSelector:
          role: mainnet-1
        replicas: 1
        resources:
          requests:
            cpu: "0.5"
            memory: 4Gi
        tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: mainnet-1
      storageClass: fsx-lustre
      storageResources:
        requests:
          storage: 5Gi
  blockValidator:
    enabled: true
    spec:
      deploymentOverrides:
        nodeSelector:
          role: mainnet-1
        replicas: 1
        resources:
          requests:
            cpu: 2
            memory: 8Gi
        tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: mainnet-1
  blockchain:
    enabled: true
    spec:
      deploymentOverrides:
        nodeSelector:
          role: mainnet-1
        replicas: 1
        resources:
          requests:
            cpu: "0.5"
            memory: 500Mi
        tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: mainnet-1
  bootstrap:
    enabled: false
    spec: {}
  coinbase:
    enabled: false
    spec:
      deploymentOverrides:
        nodeSelector:
          role: mainnet-1
        replicas: 1
        resources:
          requests:
            cpu: 1
            memory: 1Gi
        tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: mainnet-1
  configMapName: shared-config
  image: 434394763103.dkr.ecr.eu-north-1.amazonaws.com/teranode-public:v0.5.4
  legacy:
    enabled: true
    spec:
      deploymentOverrides:
        configMapName: legacy-config
        nodeSelector:
          role: mainnet-1
        replicas: 1
        resources:
          requests:
            cpu: 8
            memory: 4Gi
        tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: mainnet-1
  miner:
    enabled: false
    spec:
      deploymentOverrides:
        nodeSelector:
          role: mainnet-1
        replicas: 1
        resources:
          requests:
            cpu: 1
            memory: 1Gi
        tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: mainnet-1
  peer:
    enabled: false
    spec:
      deploymentOverrides:
        nodeSelector:
          role: mainnet-1
        replicas: 1
        resources:
          requests:
            cpu: "0.5"
            memory: 500Mi
        tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: mainnet-1
      grpcIngress:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: peer-grpc
        className: traefik-internal
        host: euw1-teranode-main-net-1-prod.ubsv.dev
      wsIngress:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: p2p-ws
        className: traefik-internal
        host: euw1-teranode-main-net-1-prod.ubsv.dev
      wssIngress:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: p2p-wss
        className: traefik-internal
        host: euw1-teranode-main-net-1-prod.ubsv.dev
  propagation:
    enabled: false
    spec:
      deploymentOverrides:
        nodeSelector:
          role: mainnet-1
        replicas: 1
        resources:
          requests:
            cpu: "0.5"
            memory: 500Mi
        tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: mainnet-1
      grpcIngress:
        annotations:
          traefik.ingress.kubernetes.io/router.entrypoints: prop-grpc
        className: traefik-internal
        host: euw1-teranode-main-net-1-prod.ubsv.dev
      serviceAnnotations:
        traefik.ingress.kubernetes.io/service.serversscheme: h2c
  subtreeValidator:
    enabled: true
    spec:
      deploymentOverrides:
        nodeSelector:
          role: mainnet-1
        replicas: 1
        resources:
          requests:
            cpu: 1
            memory: 8Gi
        tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: mainnet-1
      storageClass: fsx-lustre
      storageResources:
        requests:
          storage: 3600Gi
  utxoPersister:
    enabled: false
    spec:
      deploymentOverrides:
        nodeSelector:
          role: mainnet-1
        replicas: 1
        resources:
          requests:
            cpu: 1
            memory: 8Gi
        tolerations:
        - effect: NoSchedule
          key: role
          operator: Equal
          value: mainnet-1
  validator:
    enabled: false
    spec: {}
