apiVersion: v1
data:
  SETTINGS_CONTEXT: operator.mainnet.euw1-1
  asset_centrifuge_disable: "true"
  blockassembly_disabled: "true"
kind: ConfigMap
metadata:
  name: shared-config
  namespace: mainnet-1