apiVersion: v1
kind: PersistentVolume
metadata:
  name: propagation-luster-pv
spec:
  capacity:
    storage: 2400Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-0d78849895b00d529
    volumeAttributes:
      dnsname: fs-0d78849895b00d529.fsx.eu-west-1.amazonaws.com
      mountname: meetpbev