apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: propagation-luster-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 2400Gi
  volumeName: propagation-luster-pv
