apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/scaling-miner

namespace: m1

nameSuffix: "1"

configMapGenerator:
  - behavior: merge
    literals:
      - SETTINGS_CONTEXT=scaling.m1
    name: shared-config-m
  - behavior: merge
    literals:
      - SETTINGS_CONTEXT=scaling.m1.asset
    name: asset-config-m
  - behavior: merge
    literals:
      - SETTINGS_CONTEXT=scaling.m1.blockassembly
    name: blockassembly-config-m
  - behavior: merge
    literals:
      - SETTINGS_CONTEXT=scaling.m1.blockvalidation
    name: blockvalidation-config-m
  - behavior: merge
    literals:
      - SETTINGS_CONTEXT=scaling.m1.subtreevalidation
    name: subtreevalidation-config-m
  - behavior: merge
    literals:
      - SETTINGS_CONTEXT=scaling.m1.coinbase
    name: coinbase-config-m
  - behavior: merge
    literals:
      - SETTINGS_CONTEXT=scaling.m1.propagation
    name: propagation-config-m
  - behavior: merge
    literals:
      - SETTINGS_CONTEXT=scaling.m1.subtreeassembly
    name: subtreeassembly-config-m
patches:
  - patch: |-
      - op: replace
        path: /spec/dnsNames
        value:
         - m1.scaling.ubsv.dev
    target:
      kind: Certificate
  - patch: |-
      - op: replace
        path: /spec/routes/0/services/0/name
        value: propagation-service1
    target:
      labelSelector: service=propagation
  - patch: |-
      - op: replace
        path: /spec/routes/0/services/0/name
        value: p2p-service1
    target:
      kind: IngressRouteTCP
      labelSelector: service=p2p
  - patch: |-
      - op: replace
        path: /spec/routes/0/services/0/name
        value: coinbase-service1
    target:
      kind: IngressRouteTCP
      labelSelector: service=coinbase
  - patch: |-
      - op: replace
        path: /spec/routes/0/services/0/name
        value: asset-service1
    target:
      kind: IngressRouteTCP
      labelSelector: service=asset
  - patch: |-
      - op: replace
        path: /spec/routes/0/services/0/name
        value: asset-service1
      - op: replace
        path: /spec/routes/0/match
        value: Host(`m1.scaling.ubsv.dev`)
    target:
      kind: IngressRoute
      labelSelector: service=asset
  - patch: |-
      - op: replace
        path: /spec/routes/0/services/0/name
        value: p2p-service1
      - op: replace
        path: /spec/routes/0/match
        value: Host(`m1.scaling.ubsv.dev`)
    target:
      kind: IngressRoute
      labelSelector: service=p2p
  - patch: |-
      - op: replace
        path: /subjects/0/namespace
        value: m1
    target:
      kind: ClusterRoleBinding
  - patch: |-
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: sa-m1
    target:
      kind: Deployment
