apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - blob.yaml
  - blockvalidation.yaml
  - blob-service.yaml
  - validation-service.yaml
  - blockvalidation-service.yaml
  - tx-blaster.yaml
  - propagation-grpc-ingress.yaml
  - miner.yaml
  - propagation.yaml
  - blockassembly.yaml
  - blockchain-service.yaml
  - blockassembly-service.yaml
  - blob-http-ingress.yaml
  - blob-grpc-ingress.yaml
  - validation.yaml
  - tx-blaster-service.yaml
  - blockchain.yaml
  - propagation-service.yaml
