apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: http-80-asset
  labels:
    service: asset
spec:
  entryPoints:
    - web # Ensure this corresponds to HTTP (port 80) in Traefik
  routes:
    - match: Host(`m.scaling.ubsv.dev`)
      kind: Rule
      services:
        - name: asset-service
          port: 8090
