apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: https-443-asset
  labels:
    service: asset
spec:
  entryPoints:
    - websecure # Service port expecting HTTPS
  routes:
    - match: Host(`m.scaling.ubsv.dev`)
      kind: Rule
      services:
        - name: asset-service
          port: 8090  # Service port expecting HTTP
  tls:
    secretName: scaling-tls
