apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: m1-ingressroute-https

spec:
  entryPoints:
    - websecure
  routes:
  - match: HostSNI(`m1.scaling.ubsv.dev`)
    services:
    - name: blob-service1
      port: 8090
  tls:
    passthrough: true
