apiVersion: v1
kind: Service
metadata:
  name: blob-service

  labels:
    app: blob
  annotations:
    prometheus.io/port: "9091"
    prometheus.io/scrape: "true"
spec:
  clusterIP: None
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
  selector:
    app: blob
  ports:
    - name: blob-grpc
      port: 8091
      targetPort: 8091
      protocol: TCP
    - name: blob-http
      port: 8090
      targetPort: 8090
      protocol: TCP
    - name: profiler
      port: 9091
      targetPort: 9091
      protocol: TCP
    - name: debugger
      port: 4040
      targetPort: 4040
      protocol: TCP
    - name: p2p
      port: 9905
      targetPort: 9905
      protocol: TCP
    - name: p2p-http
      port: 9906
      targetPort: 9906
      protocol: TCP
