apiVersion: apps/v1
kind: Deployment
metadata:
  name: blob
  labels:
    app: blob
    project: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blob
  template:
    metadata:
      labels:
        app: blob
    spec:
      serviceAccountName: sa-m
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: blob
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: blob
          image: REPO:IMAGE:TAG
          args: [ "-blobserver=1" ]
          envFrom:
            - configMapRef:
                name: shared-config-m
          env:
            - name: SERVICE_NAME
              value: blob-service
            - name: subtreestore
              value: s3:///ubsv-subtree-store?region=eu-north-1&localTTLStore=file&localTTLStorePath=/data/subtreestore-ttl
          ports:
            - containerPort: 8090
              protocol: TCP
            - containerPort: 8099
              protocol: TCP
            - containerPort: 8091
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
            - containerPort: 9905
              protocol: TCP
            - containerPort: 9906
              protocol: TCP
            - containerPort: 4040
              protocol: TCP
          resources:
            requests:
              memory: 32Gi
              cpu: "8"
            limits:
              memory: 32Gi
              cpu: "16"
          volumeMounts:
            - mountPath: /data/subtreestore-ttl/
              name: subtree-store-ttl
          readinessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
      volumes:
        - name: subtree-store-ttl
          ephemeral:
            volumeClaimTemplate:
              metadata:
                labels:
                  type: subtreestore-ttl
              spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName: "io2-xfs-low-iops"
                resources:
                  requests:
                    storage: 4000Gi
