apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockassembly

  labels:
    app: blockassembly
    project: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockassembly
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: blockassembly
    spec:
      serviceAccountName: sa-m
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: blockassembly
                topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        role: blockassembly
      tolerations:
        - key: role
          value: blockassembly
          operator: Equal
          effect: NoSchedule
      containers:
        - name: blockassembly
          image: REPO:IMAGE:TAG
          imagePullPolicy: Always
          args: [ "-blockassembly=1" ]
          envFrom:
            - configMapRef:
                name: shared-config-m
            - configMapRef:
                name: blockassembly-config-m
          env:
            - name: SERVICE_NAME
              value: blockassembly-service
          ports:
            - containerPort: 8055
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
            - containerPort: 4040
              protocol: TCP
          resources:
            requests:
              memory: 475Gi
              cpu: "105"
            limits:
              memory: 475Gi
          volumeMounts:
            - name: lustre-storage
              mountPath: /data/subtreestore
            - mountPath: /data/subtreestore-ttl-1/
              name: subtree-store-ttl-1
            - mountPath: /data/subtreestore-ttl-2/
              name: subtree-store-ttl-2
            - mountPath: /data/subtreestore-ttl-3/
              name: subtree-store-ttl-3
            - mountPath: /data/subtreestore-ttl-4/
              name: subtree-store-ttl-4
          readinessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 1
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 1
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
      volumes:
        - name: lustre-storage
          persistentVolumeClaim:
            claimName: lustre-pvc
        - name: subtree-store-ttl-1
          persistentVolumeClaim:
            claimName: blockassembly-pvc-1
        - name: subtree-store-ttl-2
          persistentVolumeClaim:
            claimName: blockassembly-pvc-2
        - name: subtree-store-ttl-3
          persistentVolumeClaim:
            claimName: blockassembly-pvc-3
        - name: subtree-store-ttl-4
          persistentVolumeClaim:
            claimName: blockassembly-pvc-4
