apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blockpersister-pvc
spec:
  storageClassName: ssd-gp3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "1500Gi"

