apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: blockassembly-pvc-2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: io2-xfs-low-iops
  resources:
    requests:
      storage: 1000Gi
