apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockvalidation

  labels:
    app: blockvalidation
    project: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockvalidation
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: blockvalidation
    spec:
      serviceAccountName: sa-m
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: blockvalidation
                topologyKey: "kubernetes.io/hostname"
      tolerations:
        - key: type
          value: massive
          operator: Equal
          effect: NoSchedule
      containers:
        - name: blockvalidation
          image: REPO:IMAGE:TAG
          args: [ "-blockvalidation=1" ]
          envFrom:
            - configMapRef:
                name: shared-config-m
          env:
            - name: SERVICE_NAME
              value: blockvalidation-service
            - name: logLevel
              value: "DEBUG"
          ports:
            - containerPort: 8088
              protocol: TCP
            - containerPort: 8288
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
            - containerPort: 4040
              protocol: TCP
          resources:
            requests:
              memory: 400Gi
              cpu: "120"
            limits:
              memory: 400Gi
              cpu: "120"
          volumeMounts:
            - mountPath: /data/subtreestore-ttl/
              name: subtree-store-ttl
          readinessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 1
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 1
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
      volumes:
        - name: subtree-store-ttl
          ephemeral:
            volumeClaimTemplate:
              metadata:
                labels:
                  type: subtreestore-ttl
              spec:
                accessModes: [ "ReadWriteOnce" ]
                storageClassName: "io2-xfs-low-iops"
                resources:
                  requests:
                    storage: 4000Gi
