apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockvalidation

  labels:
    app: blockvalidation
    project: service
spec:
  replicas: 0
  selector:
    matchLabels:
      app: blockvalidation
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: blockvalidation
    spec:
      serviceAccountName: s3-push-service-account
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: blockvalidation
                topologyKey: "kubernetes.io/hostname"
      containers:
        - name: blockvalidation
          image: 434394763103.dkr.ecr.eu-north-1.amazonaws.com/IMAGE:TAG
          args: [ "-blockvalidation=1" ]
          env:
            - name: SETTINGS_CONTEXT
              value: scaling-miner.m1
            - name: JAEGER_AGENT_HOST
              value: jaeger-cluster-agent.jaeger.svc.cluster.local
            - name: JAEGER_AGENT_PORT
              value: "6831"
            - name: SERVICE_NAME
              value: blockvalidation-service
          ports:
            - containerPort: 8088
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
            - containerPort: 4040
              protocol: TCP
          resources:
            requests:
              memory: 10Gi
              cpu: "4"
            limits:
              memory: 10Gi
              cpu: "4"
          readinessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
