apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockvalidation

  labels:
    app: blockvalidation
    project: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockvalidation
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: blockvalidation
    spec:
      serviceAccountName: sa-m
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: blockvalidation
                topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        role: blockvalidation
      tolerations:
        - key: role
          value: blockvalidation
          operator: Equal
          effect: NoSchedule
      containers:
        - name: blockvalidation
          image: REPO:IMAGE:TAG
          args: ["-blockvalidation=1"]
          envFrom:
            - configMapRef:
                name: shared-config-m
            - configMapRef:
                name: blockvalidation-config-m
          env:
            - name: SERVICE_NAME
              value: blockvalidation-service
          ports:
            - containerPort: 8088
              protocol: TCP
            - containerPort: 8288
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
            - containerPort: 4040
              protocol: TCP
          resources:
            requests:
              memory: 1456Gi
              cpu: "125"
            limits:
              memory: 1456Gi
          volumeMounts:
            - name: lustre-storage
              mountPath: /data/subtreestore

          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 9091
          #   initialDelaySeconds: 1
          #   periodSeconds: 10
          #   failureThreshold: 5
          #   timeoutSeconds: 10
          # livenessProbe:
          #   httpGet:
          #     path: /health
          #     port: 9091
          #   initialDelaySeconds: 1
          #   periodSeconds: 10
          #   failureThreshold: 5
          #   timeoutSeconds: 10
      volumes:
        - name: lustre-storage
          persistentVolumeClaim:
            claimName: lustre-pvc
