apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinbase
  namespace: coinbase-service
  labels:
    app: coinbase
    project: service
spec:
  replicas: 0
  selector:
    matchLabels:
      app: coinbase
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0

  template:
    metadata:
      labels:
        app: coinbase
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: coinbase
                topologyKey: "kubernetes.io/hostname"
      tolerations:
        - key: service
          value: coinbase
          operator: Equal
          effect: NoSchedule
      containers:
        - name: coinbase
          image: REPO:IMAGE:TAG
          args: ["-coinbase=1"]
          envFrom:
            - configMapRef:
                name: shared-config-m
            - configMapRef:
                name: coinbase-config-m
          env:
            - name: SERVICE_NAME
              value: coinbase-service
            - name: logLevel
              value: DEBUG
            - name: slack_channel
              valueFrom:
                secretKeyRef:
                  name: ubsv-secrets
                  key: slack_channel
            - name: slack_token
              valueFrom:
                secretKeyRef:
                  name: ubsv-secrets
                  key: slack_token
          ports:
            - containerPort: 8093
              protocol: TCP
            - containerPort: 9091
              protocol: TCP
            - containerPort: 4040
              protocol: TCP
          resources:
            requests:
              memory: 5Gi
              cpu: "2"
            limits:
              memory: 5Gi
          readinessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 1
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 1
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
