apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - asset.yaml
  - blockvalidation.yaml
  - propagation-service.yaml
  - utxostore-service.yaml
  - txmetastore-service.yaml
  - utxo-config-map.yaml
  - blockvalidation-service.yaml
  - miner-deployment.yaml
  - blockassembly-blaster-service.yaml
  - tx-blaster-service.yaml
  - validation-service.yaml
  - propagation.yaml
  - utxostore.yaml
  - txmetastore.yaml
  - blockassembly.yaml
  - validation.yaml
  - asset-service.yaml
  - blockchain-service.yaml
  - asset-http-ingress.yaml
  - asset-grpc-ingress.yaml
  - blockassembly-blaster.yaml
  - tx-blaster.yaml
  - propagation-grpc-ingress.yaml
  - blockchain.yaml
  - blockassembly-service.yaml
  - shared-config-map.yaml
  - service-account.yaml
  - cluster-role-binding.yaml
  - coinbase-service.yaml
  - coinbase-deployment.yaml
  - coinbase-grpc-ingress.yaml
  - propagation-drpc-ingress.yaml
  - propagation-frpc-ingress.yaml
  - p2p.yaml
  - p2p-service.yaml
  - p2p-ingress.yaml
  - p2p-ws-ingress.yaml
  - p2p-grpc-ingress.yaml
