apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-pv
spec:
  capacity:
    storage: 2400Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  persistentVolumeReclaimPolicy: Recycle
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-006930142645b417e
    volumeAttributes:
      dnsname: fs-006930142645b417e.fsx.eu-west-1.amazonaws.com
      mountname: isxdjbev
