apiVersion: v1
kind: PersistentVolume
metadata:
  name: fsx-pv
spec:
  capacity:
    storage: 2400Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  mountOptions:
    - flock
  persistentVolumeReclaimPolicy: Recycle
  csi:
    driver: fsx.csi.aws.com
    volumeHandle: fs-01f6089f15367dc88
    volumeAttributes:
      dnsname: fs-01f6089f15367dc88.fsx.us-east-1.amazonaws.com
      mountname: posdlb4v
