apiVersion: v1
kind: Service
metadata:
  name: nginx-service

  labels:
    app: nginx
spec:
  clusterIP: None
  ipFamilyPolicy: SingleStack
  ipFamilies:
  - IPv4
  selector:
    app: nginx
  ports:
    - name: nginx-http
      port: 5555
      targetPort: 80
      protocol: TCP