apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    project: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
          protocol: TCP
        resources:
          requests:
            memory: "4Gi"
            cpu: "2"
          limits:
            memory: "4Gi"
            cpu: "2"
        volumeMounts:
        - mountPath: /usr/share/nginx/html/
          name: nginx-html
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 1
          periodSeconds: 10
          failureThreshold: 5
          timeoutSeconds: 3
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 1
          periodSeconds: 10
          failureThreshold: 5
          timeoutSeconds: 3
      volumes:
      - name: nginx-html
        ephemeral:
          volumeClaimTemplate:
            metadata:
              labels:
                type: subtreestore-ttl
            spec:
              accessModes: ["ReadWriteOnce"]
              storageClassName: "io2-xfs-low-iops"
              resources:
                requests:
                  storage: "50Mi"
