apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-html
spec:
  accessModes:
    - ReadWriteOnce  # Adjust access mode as needed
  resources:
    requests:
      storage: 50Mi  # Specify the desired storage size
       