apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: p2p-ws-ingress-9906
  labels:
    service: p2p
spec:
  entryPoints:
    - p2p-ws
  routes:
    - match: HostSNI(`m1.scaling.ubsv.dev`)
      services:
        - name: asset-service
          port: 9906
  tls:
    passthrough: true
