apiVersion: apps/v1
kind: Deployment
metadata:
  name: propagation

  labels:
    app: propagation
    project: service
spec:
  replicas: 16
  selector:
    matchLabels:
      app: propagation
  template:
    metadata:
      labels:
        app: propagation
    spec:
      serviceAccountName: sa-m
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: propagation
                topologyKey: "kubernetes.io/hostname"
      tolerations:
        - key: role
          value: propagation
          operator: Equal
          effect: NoSchedule
      nodeSelector:
        role: propagation
      containers:
        - name: propagation
          image: REPO:IMAGE:TAG
          args: [ "-propagation=1" ]
          # command: "You can override the entrypoint with a command."
          #          command: ["./dlv", "--listen=:4040", "--continue", "--accept-multiclient", "--headless=true", "--api-version=2", "exec", "./ubsv.run", "--"]
          #          command: [ "./ubsv.run" ]
          envFrom:
            - configMapRef:
                name: shared-config-m
            - configMapRef:
                name: propagation-config-m
          env:
            - name: SERVICE_NAME
              value: propagation-service
          ports:
            - containerPort: 4040
              protocol: TCP
            - containerPort: 8833
              protocol: TCP
            - containerPort: 8084
              protocol: TCP
            - containerPort: 8384
              protocol: UDP
          resources:
            requests:
              memory: 100Gi
              cpu: "50"
            limits:
              memory: 100Gi
          readinessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 1
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 1
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
          volumeMounts:
            - name: lustre-storage
              mountPath: /data/txstore
            - name: scaling-tls
              mountPath: /app/certs
              readOnly: true
      volumes:
        - name: lustre-storage
          persistentVolumeClaim:
            claimName: propagation-luster-pvc
        - name: scaling-tls
          secret:
            secretName: scaling-tls
            items:
              - key: tls.crt
                path: ubsv.crt
              - key: tls.key
                path: ubsv.key