apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: m1-ingressroute-tcp-8184

spec:
  entryPoints:
    - prop-drpc
  routes:
  - match: HostSNI(`m1.scaling.ubsv.dev`)
    services:
    - name: propagation-service1
      port: 8184
  tls:
    passthrough: true
