apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: status-ingress-9908
  labels:
    service: status
spec:
  entryPoints:
    - status
  routes:
    - match: HostSNI(`m1.scaling.ubsv.dev`)
      services:
        - name: status-service
          port: 9908
  tls:
    passthrough: true
