apiVersion: apps/v1
kind: Deployment
metadata:
  name: subtreeassembly

  labels:
    app: subtreeassembly
    project: service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: subtreeassembly
  template:
    metadata:
      labels:
        app: subtreeassembly
    spec:
      serviceAccountName: sa-m
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    app: subtreeassembly
                topologyKey: "kubernetes.io/hostname"
      nodeSelector:
        role: subtreeassembly
      tolerations:
        - key: role
          value: subtreeassembly
          operator: Equal
          effect: NoSchedule
      containers:
        - name: subtreeassembly
          image: REPO:IMAGE:TAG
          args: [ "-subtreeassembly=1" ]
          # command: "You can override the entrypoint with a command."
          #          command: ["./dlv", "--listen=:4040", "--continue", "--accept-multiclient", "--headless=true", "--api-version=2", "exec", "./ubsv.run", "--"]
          #          command: [ "./ubsv.run" ]
          envFrom:
            - configMapRef:
                name: shared-config-m
            - configMapRef:
                name: subtreeassembly-config-m
          env:
            - name: SERVICE_NAME
              value: subtreeassembly-service
          ports:
            - containerPort: 4040
              protocol: TCP
          resources:
            requests:
              memory: 512Gi
              cpu: "50"
            limits:
              memory: 512Gi
          readinessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 1
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 9091
            initialDelaySeconds: 1
            periodSeconds: 10
            failureThreshold: 5
            timeoutSeconds: 3
          volumeMounts:
            - name: lustre-storage
              mountPath: /data/subtreestore
            - name: scaling-tls
              mountPath: /app/certs
              readOnly: true
      volumes:
        - name: lustre-storage
          persistentVolumeClaim:
            claimName: lustre-pvc
        - name: scaling-tls
          secret:
            secretName: scaling-tls
            items:
              - key: tls.crt
                path: ubsv.crt
              - key: tls.key
                path: ubsv.key