// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: services/cleanup/cleanup_api/cleanup_api.proto

package cleanup_api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CleanupAPI_HealthGRPC_FullMethodName = "/cleanup.CleanupAPI/HealthGRPC"
)

// CleanupAPIClient is the client API for CleanupAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CleanupAPIClient interface {
	HealthGRPC(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*HealthResponse, error)
}

type cleanupAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewCleanupAPIClient(cc grpc.ClientConnInterface) CleanupAPIClient {
	return &cleanupAPIClient{cc}
}

func (c *cleanupAPIClient) HealthGRPC(ctx context.Context, in *EmptyMessage, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, CleanupAPI_HealthGRPC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CleanupAPIServer is the server API for CleanupAPI service.
// All implementations must embed UnimplementedCleanupAPIServer
// for forward compatibility.
type CleanupAPIServer interface {
	HealthGRPC(context.Context, *EmptyMessage) (*HealthResponse, error)
	mustEmbedUnimplementedCleanupAPIServer()
}

// UnimplementedCleanupAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCleanupAPIServer struct{}

func (UnimplementedCleanupAPIServer) HealthGRPC(context.Context, *EmptyMessage) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthGRPC not implemented")
}
func (UnimplementedCleanupAPIServer) mustEmbedUnimplementedCleanupAPIServer() {}
func (UnimplementedCleanupAPIServer) testEmbeddedByValue()                    {}

// UnsafeCleanupAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CleanupAPIServer will
// result in compilation errors.
type UnsafeCleanupAPIServer interface {
	mustEmbedUnimplementedCleanupAPIServer()
}

func RegisterCleanupAPIServer(s grpc.ServiceRegistrar, srv CleanupAPIServer) {
	// If the following call pancis, it indicates UnimplementedCleanupAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CleanupAPI_ServiceDesc, srv)
}

func _CleanupAPI_HealthGRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmptyMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CleanupAPIServer).HealthGRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CleanupAPI_HealthGRPC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CleanupAPIServer).HealthGRPC(ctx, req.(*EmptyMessage))
	}
	return interceptor(ctx, in, info, handler)
}

// CleanupAPI_ServiceDesc is the grpc.ServiceDesc for CleanupAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CleanupAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "cleanup.CleanupAPI",
	HandlerType: (*CleanupAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthGRPC",
			Handler:    _CleanupAPI_HealthGRPC_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/cleanup/cleanup_api/cleanup_api.proto",
}
